name: Dispatch
on:
  push:
    branches: [dispatch-*] 

jobs:
  dispatch:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - name: Repository Dispatch
        uses: peter-evans/repository-dispatch@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          repository: yu-fukunaga/practice-github-actions
          event-type: dispatch-test 
          client-payload: '{"ref": "${{ github.ref }}", "sha": "${{ github.sha }}"}'
        