name: dispatch test

on:
    repository_dispatch:
      types: [ dispatch-test ]
  
jobs:
  torigger:
    name: commit
    permissions:
      id-token: write
      contents: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: BRANCH=dispatch-test ./scripts/commit.sh
        env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}